
-- What is the total revenue generated by each customer segment?
select customer_segment, sum(total_sales) from global_ecommerce_sales 
group by customer_segment
-- ------------------------------------


-- What is the total revenue generated by each region?
select region, sum(total_sales) from global_ecommerce_sales 
group by region
-- ----------------------------------------


-- What is the total revenue generated by each product category?
select product_category , sum(total_sales) from global_ecommerce_sales 
group by product_category
-- ----------------------------------------------------


-- Which countries generated more than $20,000 in total revenue?
select country, sum(total_sales) from global_ecommerce_sales
group by country
having sum(total_sales)>20000
