
-- Calculate revenue for each order and classify the orders as Profitable or Not Profitable based on the Profit column.
select order_id , total_sales, profit,
case
	when profit>0 then 'Profitable'
	when profit<0 then 'Non Profitable'
	else 'Break-even'
end as profit_status
from global_ecommerce_sales
-- --------------------------------------------------


-- Count how many orders belong to each Quantity_Level (Low, Medium, High).
select 
case
	when quantity BETWEEN 1 AND 5 then 'Low'
	when quantity BETWEEN 6 AND 10 then 'Medium'
	when quantity>10 then 'High'	
end as Quantity_Level,
count(order_id) as total_order
from global_ecommerce_sales
group by Quantity_Level
-- ---------------------------------------------


-- Calculate the total revenue generated by each Price_Level.
select 
case
	when unit_price<100 then 'Budget'
	when unit_price between 100 and 300 then 'Mid-Range'
	when unit_price>300 then 'Premium'
end as Price_Level,
sum(total_sales )
from global_ecommerce_sales
group by Price_Level
-- -----------------------------------------------------


-- Calculate the total revenue for each year.
select year(order_date) as year, 
sum(total_sales) as sales_by_year
from global_ecommerce_sales
group by year
-- ------------------------------------------------


-- Calculate the monthly revenue for the entire dataset.
select month(order_date) as month, year(order_date) as year, 
sum(total_sales) as monthly_sales
from global_ecommerce_sales
group by month, year
-- -----------------------------------------------------


-- Find the month with the highest total revenue.
select month(order_date) as month, year(order_date) as year, 
sum(total_sales) as monthly_sales
from global_ecommerce_sales
group by month, year
order by monthly_sales desc
limit 1
-- -----------------------------------------------


-- Calculate the average monthly revenue for each year.
with cte as(
	select year(order_date) as year, month(order_date) as month ,
	sum(total_sales) as monthly_sales
	from global_ecommerce_sales
	group by month, year
)
select year, avg(monthly_sales) as avg_monthly_revenue
from cte 
group by year
order by year
-- ---------------------------------------------


-- Find the year with the highest total revenue.
select year(order_date) as year, 
sum(total_sales) as yearly_sales
from global_ecommerce_sales
group by year
order by yearly_sales desc
limit 1

